### ISSUE TITLE
Custom items don't show up with the new MenuItem solution

### ISSUE THREAD

**Issue by zsombornagy** [danielsaidi/Sheeeeeeeeet#108] opened 2019-10-03 14:08 UTC
Hi!

With the previous version I was able to do a custom item where I added an image view to the right side.
It looked like this:

```
class RightImageItem: ActionSheetItem {
    open override func cell(for tableView: UITableView) -> ActionSheetItemCell {
        return RightImageItemCell(style: cellStyle, reuseIdentifier: cellReuseIdentifier)
    }
}

class RightImageItemCell: ActionSheetItemCell {
    
    var rightImageView: UIImageView?
    
    override func refresh() {
        separatorInset = .zero
        guard let item = item else { return }
        if rightImageView == nil, let image = item.image {
            let imageView = UIImageView(image: image)
            contentView.addSubview(imageView)
            imageView.autoPinEdge(toSuperviewMargin: .trailing)
            imageView.autoAlignAxis(toSuperviewAxis: .horizontal)
            imageView.contentMode = .scaleAspectFit
            rightImageView = imageView
        }
        rightImageView?.image = item.image
        selectionStyle = item.tapBehavior == .none ? .none : .default
        textLabel?.font = titleFont
        textLabel?.text = item.title
        textLabel?.textAlignment = .left
        textLabel?.textColor = titleColor
        detailTextLabel?.font = subtitleFont
        detailTextLabel?.text = item.subtitle
        detailTextLabel?.textColor = subtitleColor
    }
}
```

Well, a little bit hacky, but it worked.

Now I tried to convert it into the new MenuItem solution like this:

```
class RightImageItem: MenuItem {
    
    open override func actionSheetCell(for tableView: UITableView) -> ActionSheetItemCell {
        RightImageItemCell(style: .default)
    }
    
    open override var actionSheetCellType: ActionSheetItemCell.Type {
        RightImageItemCell.self
    }
}

class RightImageItemCell: ActionSheetItemCell {
    
    var rightImageView: UIImageView?

    override func refresh() {
        super.refresh()
        guard let item = item else { return }

        if rightImageView == nil, let image = item.image {
            let imageView = UIImageView(image: image)
            contentView.addSubview(imageView)
            imageView.autoPinEdge(toSuperviewMargin: .trailing)
            imageView.autoAlignAxis(toSuperviewAxis: .horizontal)
            imageView.contentMode = .scaleAspectFit
            rightImageView = imageView
        }
        rightImageView?.image = item.image
        imageView?.image = nil
    }
}
```

And when I use these items, they just don't show up. The item table view is just empty.
I was trying to debug it, and what I found is that the `ActionSheetItemHandler`'s `numberOfRowsInSection` is called, and it returns the correct number (3 items in my case), but `cellForRowAt indexPath` is never called by the system.

What am I doing wrong?

Thanks!

**Comment by danielsaidi** [comment] 2019-10-04 10:12
Hi! Sorry to hear that you experience problems with the new model. I'll look into it asap!

**Comment by zsombornagy** [comment] 2019-10-09 07:02
Hi!

Did you have a chance to look into this?

Thank you!

**Comment by danielsaidi** [comment] 2019-10-09 08:01
Hi! Sorry, I've been busy with other projects, but I will asap!

**Comment by zsombornagy** [comment] 2019-10-09 08:08
(you shouldn't be sorry, I'm using your great library for free, I don't think you have an obligation to fix my problems :)

**Comment by danielsaidi** [comment] 2019-10-10 07:00
Haha, but I want to :)

**Comment by danielsaidi** [comment] 2019-10-10 07:00
I'm adding this to the 3.0.2 milestone, which I hope will be done in a couple of days.

**Comment by danielsaidi** [comment] 2019-10-10 19:27
@zsombornagy Just so that I understand. If you place a breakpoint in `ActionSheetItemHandler` at line `67` (the first line of the `cellForRowAt` implementation) in the demo app and open a menu, is that function never called? It's called for me, once for every item.

**Comment by danielsaidi** [comment] 2019-10-10 19:48
@zsombornagy I think I've figured out your problem.

I can't reproduce the problem you describe with `cellForRowAt` not being called (it is for me), but I can reproduce the problem where items don't show up.

I used your class and removed a bunch of stuff from it, so that it looks like this:

```
class RightImageItem: MenuItem {
    
    override func actionSheetCell(for tableView: UITableView) -> ActionSheetItemCell {
        RightImageItemCell(style: preferredActionSheetCellStyle)
    }

    open override var actionSheetCellType: ActionSheetItemCell.Type {
        RightImageItemCell.self
    }
}

class RightImageItemCell: ActionSheetItemCell {

    var rightImageView: UIImageView?

    override func refresh() {
        super.refresh()
        contentView.backgroundColor = .red
    }
}
```

As you can see, it's just a standard item with a cell that sets its background to red when it's refreshed.

I then adjusted `FoodOption+ActionSheetItems` to return this item instead of a regular one:

```
func toMenuItem() -> MenuItem {
    RightImageItem(
        title: title,
        subtitle: subtitle,
        value: self,
        image: image
    )
}
```

When I then run the app, this is what I see:

![Simulator Screen Shot - iPhone 11 - 2019-10-10 at 21 37 59](https://user-images.githubusercontent.com/429927/66600654-423e7a00-eba6-11e9-9e5a-aec151829c8b.png)

Judging from your description, I take it that this is what happens to you as well, right?

I then realized that 3.0's new cell height logic uses appearance proxies instead of the previous static property approach. However, when Sheeeeeeeeet resolves the height of each cell, it looks at each concrete type. The problem with this is that if `ActionSheetItemCell.appearance().height = 55` still means that `RightImageItemCell.appearance().height` is `nil`, since the inheritance value isn't applied until the view is sent to the screen.

By adding a `RightImageItemCell.appearance().height = 123` to the appearance, I got this result:

![Simulator Screen Shot - iPhone 11 - 2019-10-10 at 21 42 25](https://user-images.githubusercontent.com/429927/66600892-ddcfea80-eba6-11e9-9837-af6a5db0e4da.png)

I think I mention this in the docs, and if you look in `ActionSheetAppearance`'s `applyHeights()` you can see that I apply the height of each item type. 

However, it is a horrible design flaw and I will try to solve it in another way. Stay tuned :)

Can you please verify that setting a concrete height for `RightImageItemCell` solves your problems as well?

**Comment by danielsaidi** [comment] 2019-10-10 22:15
I think I was able to solve this problem! I recursively resolve the item height, instead of requiring a proxy registration for each class.

The fix is merged to `master` and can be tested before I bump the library version.

**Comment by danielsaidi** [comment] 2019-10-10 22:26
I close this issue now, merge to master and bump the library to `3.0.2`. Just let me know if the fixed didn't work for you and I'll reopen the ticked.

**Closed by danielsaidi** 2019-10-10 22:26 UTC
Labels: bug

**Comment by zsombornagy** [comment] 2019-10-11 09:30
Awesome! This must be exactly what was wrong in my case, I will try 3.0.2 as soon as I can.
Thank you!

**Comment by danielsaidi** [comment] 2019-10-11 09:35
Perfect! Let me know if it solved your problem and if there are other problems with custom types as well. The demo app should have a couple of custom items.

**Comment by zsombornagy** [comment] 2019-10-11 10:33
With version 3.0.2, everything works great! Thank you again!

**Comment by danielsaidi** [comment] 2019-10-11 11:05
Perfect!
