### ISSUE TITLE
Presenting an ActionSheet from a UITabBarController gets hidden underneath the TabBar

### ISSUE THREAD

**Issue by laus102** [danielsaidi/Sheeeeeeeeet#46] opened 2018-10-02 21:36 UTC
`actionSheet.present(in: self, from: self.view)` where `self` is a `UITabBarController` subclass, the sheet gets hidden below the tab bar.  

Any thoughts on this?

**Comment by danielsaidi** [comment] 2018-10-02 21:52
Is this a new behavior since iOS 12? I use `Sheeeeeeeeet` in apps with a tab bar controller, and it is presented above the tab bar. What happens if you present it in the active vc instead?

**Comment by laus102** [comment] 2018-10-02 21:56
Re iOS12: it's possible.  @danielsaidi in both cases, it shows up behind the tabBar for me.  Do I need to take any precautions when presenting from a UITabBarController, or should it just work?  I just want to make sure I'm not doing anything stupid.  

This is the code I am using to reproduce the sheet behind the tabbar:

```
func actionSheetTest() {
        let actionSheet = ActionSheet(items: [ActionSheetCancelButton(title: "Cancel")]) { (sheet, item) in }
        actionSheet.present(in: self, from: self.view)
    }
```

**Comment by danielsaidi** [comment] 2018-10-03 05:12
Great, thanks for the additional info! I will have a look at it asap. It behaves correctly in an app of mine when built for iOS 12, so perhaps you’ve found a bug :)

**Comment by danielsaidi** [comment] 2018-10-07 09:41
Hi again,

I can't seem to reproduce the bug. I have added a tab controller to the example app, which worked without any problems with the existing code. I have pushed that version, so you could move your code to the example app to see if you can reproduce your problem with that setup. 

I then added your `asyncAfter` delay, which also worked, then adjusted the presentation code in the example app's `ViewController+TableView.swift` file to go from this:

```swift
sheet.present(in: self, from: cell.textLabel)
```

to this:

```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            sheet.present(in: self.tabBarController!, from: self.tabBarController!.view)
        }
```

This also works. The action sheet is presented above the tab bar controller.

However, as I looked at your code, I noticed some things that you could try in your setup, to see if it solves the problem: 

- The sheet should be presented from the view controller, not the tab bar controller. The library will take care of presenting the sheet properly, regardless of the view controller setup. In the example app, presenting from the tab bar controller still works, though, but when I use this library, I use the view controller that triggers the action sheet display as `in` parameter.

- `from` is actually the view that triggered the action sheet, e.g. a button or a bar button item. This value will be used whenever the action sheet is presented in a popover.

Could you try running the example app and see if you get it to work there?

**Comment by danielsaidi** [comment] 2018-10-12 08:11
Let me know if the problem remains, otherwise I'll close this in a couple of days. You can always come back later, and we'll reopen it if you've found a way to reproduce the error or if you could send me a project to look at, where the problem is present.

**Comment by danielsaidi** [comment] 2018-10-17 13:37
Closing this, since I haven't hard back from you and can't reproduce the issue. Feel free to reopen if you still have the problem.

**Closed by danielsaidi** 2018-10-17 13:37 UTC
Labels: bug

**Comment by laus102** [comment] 2018-10-17 16:01
Daniel,

Sorry I haven't responded.  Yes, it just seemed to fix itself one day.
I'll let you know if I see it again though.

Cheers
--
Brendan
