### ISSUE TITLE
Can an item with subtitle be align to center?

### ISSUE THREAD

**Issue by elanovasconcelos** [danielsaidi/Sheeeeeeeeet#142] opened 2020-09-15 17:15 UTC
I'm trying to get as much as possible to the native appearance of an action sheet, but I need a subtitle for one of the items. I cannot manager to align an item to the **center**. Is it possible?

![IMG_6927887B7B49-1](https://user-images.githubusercontent.com/7820354/93242762-acb84c80-f75d-11ea-89ec-af22ec27ae36.jpeg)

**Comment by danielsaidi** [comment] 2020-09-15 18:46
I sat with this yesterday, after some time away from this library. I first improved RTL support for when the current locale prefers RTL. That now works perfectly for all items.

I then tried to solve this bug, when you manually set the item text alignment. It has never worked for detail cells, and I didn't get it to work now either.

The problem is that the label frames are only as wide as the texts, unlike the regular item, where the label frame spans across the entire cell. 

@mohammadghk made it work with constraints, but the fix affected the cells in a way that made me decide not to add it to the library. I was thinking about opening up the library's text alignment logic for modifications, to make it possible to inject functionality like the one @mohammadghk wrote. I haven't done so yet, though.

**Comment by danielsaidi** [comment] 2020-09-15 20:48
With that said, I'd love to review a PR with a clean solution to this problem :)

**Comment by elanovasconcelos** [comment] 2020-09-15 21:01
I'm trying to create custom tableCell to use with the others, but because the cell view is from a xib file I didn't manager to use it. The labels are always nil...

do you have an example how to use a custom view?

**Comment by danielsaidi** [comment] 2020-09-15 21:26
Hmmmm, have a look at how the demo handles custom items and collections. Those item types use xibs, but require another setup than standard table view cells.

**Comment by danielsaidi** [comment] 2020-10-12 18:21
I can't get this to work, so I'm closing this. It will be a non-issue when I add SwiftUI support to the library.

**Closed by danielsaidi** 2020-10-12 18:21 UTC
